// Danh sách tỉnh - Chỉ tập trung vào Đồng Nai
export const provinces = ["Đồng Nai"]

// Danh sách huyện/thành phố của Đồng Nai (cập nhật sau sáp nhập 2025)
const districtData: Record<string, string[]> = {
  "Đồng Nai": [
    "Khu vực Biên Hòa",
    "Khu vực Long Khánh",
    "Khu vực Tân Phú",
    "Khu vực Vĩnh Cửu",
    "Khu vực Định Quán",
    "Khu vực Trảng Bom",
    "Khu vực Long Thành",
    "Khu vực Cẩm Mỹ",
    "Khu vực Thống Nhất",
    "Khu vực Xuân Lộc",
    "Khu vực Nhơn Trạch",
    "Khu vực Chơn Thành",
    "Khu vực Đồng Phú",
    "Khu vực Hớn Quản",
    "Khu vực Lộc Ninh",
    "Khu vực Bù Đốp",
    "Khu vực Bù Gia Mập",
    "Khu vực Phú Riềng",
    "Khu vực Bù Đăng",
    "Khu vực Đồng Xoài",
    "Khu vực Bình Long",
    "Khu vực Phước Long",
  ],
}

// Danh sách phường/xã của Đồng Nai (cập nhật sau sáp nhập 2025)
const wardData: Record<string, Record<string, string[]>> = {
  "Đồng Nai": {
    "Khu vực Biên Hòa": [
      "Phường Biên Hòa",
      "Phường Trấn Biên",
      "Phường Trảng Dài",
      "Phường Tam Hiệp",
      "Phường Long Bình",
      "Phường Hố Nai",
      "Phường Long Hưng",
      "Phường Phước Tân",
      "Phường Tam Phước",
    ],
    "Khu vực Long Khánh": [
      "Phường Long Khánh",
      "Phường Bảo Vinh",
      "Phường Xuân Lập",
      "Phường Hàng Gòn",
      "Phường Bình Lộc",
    ],
    "Khu vực Tân Phú": [
      "Xã Tân Phú",
      "Xã Đak Lua",
      "Xã Nam Cát Tiên",
      "Xã Tài Lài",
      "Xã Phú Lâm",
    ],
    "Khu vực Trảng Bom": [
      "Xã Trảng Bom",
      "Xã An Viễn",
      "Xã Bàu Hàm",
      "Xã Hưng Thịnh",
      "Xã Bình Minh",
    ],
    "Khu vực Xuân Lộc": [
      "Xã Xuân Định",
      "Xã Xuân Phú",
      "Xã Xuân Hòa",
      "Xã Xuân Lộc",
      "Xã Xuân Thành",
      "Xã Xuân Bắc",
    ],
    "Khu vực Cẩm Mỹ": [
      "Xã Cẩm Mỹ",
      "Xã Sông Ray",
      "Xã Xuân Quế",
      "Xã Xuân Đường",
      "Xã Xuân Đông",
    ],
    "Khu vực Long Thành": [
      "Xã An Phước",
      "Xã Bình An",
      "Xã Long Thành",
      "Xã Long Phước",
      "Xã Phước Thái",
    ],
    "Khu vực Nhơn Trạch": [
      "Xã Nhơn Trạch",
      "Xã Phước An",
      "Xã Đại Phước",
    ],
    "Khu vực Thống Nhất": [
      "Xã Dầu Giây",
      "Xã Gia Kiệm",
      "Xã Thống Nhất",
    ],
    "Khu vực Định Quán": [
      "Xã Định Quán",
      "Xã Thanh Sơn",
      "Xã Phú Hoà",
      "Xã Phú Vinh",
      "Xã La Ngà",
    ],
    "Khu vực Vĩnh Cửu": [
      "Xã Trị An",
      "Xã Phú Lý",
      "Xã Tân An",
      "Xã Tân Triều",
    ],
    "Khu vực Chơn Thành": [
      "Phường Minh Hưng",
      "Phường Chơn Thành",
      "Xã Nha Bích",
    ],
    "Khu vực Đồng Phú": [
      "Xã Đồng Tâm",
      "Xã Đồng Phú",
      "Xã Tân Lợi",
      "Xã Thuận Lợi",
    ],
    "Khu vực Hớn Quản": [
      "Xã Tân Quan ",
      "Xã Tân Khai",
      "Xã Tân Hưng",
      "Xã Minh Đức",
    ],
    "Khu vực Lộc Ninh": [
      "Xã Lộc Ninh",
      "Xã Lộc Hưng",
      "Xã Lộc Tấn",
      "Xã Lộc Thạnh",
      "Xã Lộc Thành",
      "Xã Lộc Quang",
    ],
    "Khu vực Bù Đốp": [
      "Xã Tân Tiến",
      "Xã Thiện Hưng",
      "Xã Hưng Phước",
    ],
    "Khu vực Bù Gia Mập": [
      "Xã Bù Gia Mập",
      "Xã Đăk Ơ",
      "Xã Đa Kia",
      "Xã Phú Nghĩa",
    ],
    "Khu vực Phú Riềng": [
      "Xã Bình Tân",
      "Xã Long Hà",
      "Xã Phú Riềng",
      "Xã Phú Trung",
    ],
    "Khu vực Bù Đăng": [
      "Xã Phước Sơn",
      "Xã Nghĩa Trung",
      "Xã Bù Đăng",
      "Xã Thọ Sơn",
      "Xã Đak Nhau",
      "Xã Bom Bo",
    ],
    "Khu vực Đồng Xoài": [
      "Phường Đồng Xoài",
      "Phường Bình Phước",
    ],
    "Khu vực Bình Long": [
      "Phường Bình Long",
      "Phường An Lộc",
    ],
    "Khu vực Phước Long": [
      "Phường Phước Long",
      "Phường Phước Bình",
    ],
  },
}

export function getDistricts(province: string): string[] {
  return districtData[province] || []
}

export function getWards(province: string, district: string): string[] {
  return wardData[province]?.[district] || []
}

// Dữ liệu giá đất Đồng Nai (cập nhật 2025)
export const landPriceData = [
  // TP. Biên Hòa
  {
    province: "Đồng Nai",
    district: "TP. Biên Hòa",
    ward: "Phường Biên Hòa",
    street: "Đường Nguyễn Huệ",
    minPrice: 85000000,
    maxPrice: 120000000,
    landType: "Thương mại-Dịch vụ",
  },
  {
    province: "Đồng Nai",
    district: "TP. Biên Hòa",
    ward: "Phường Biên Hòa",
    street: "Đường Trần Phú",
    minPrice: 75000000,
    maxPrice: 105000000,
    landType: "Thương mại-Dịch vụ",
  },
  {
    province: "Đồng Nai",
    district: "TP. Biên Hòa",
    ward: "Phường Trấn Biên",
    street: "Đường Võ Thị Sáu",
    minPrice: 65000000,
    maxPrice: 95000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "TP. Biên Hòa",
    ward: "Phường Trảng Dài",
    street: "Đường Bùi Trọng Nghĩa",
    minPrice: 55000000,
    maxPrice: 80000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "TP. Biên Hòa",
    ward: "Phường Tam Hiệp",
    street: "Đường Trần Quốc Toản",
    minPrice: 60000000,
    maxPrice: 90000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "TP. Biên Hòa",
    ward: "Phường Long Bình",
    street: "Đường Thân Nhân Trung",
    minPrice: 70000000,
    maxPrice: 100000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "TP. Biên Hòa",
    ward: "Phường Hố Nai",
    street: "Quốc lộ 1A",
    minPrice: 50000000,
    maxPrice: 75000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "TP. Biên Hòa",
    ward: "Phường Long Hưng",
    street: "Đường Nguyễn Văn Tỏ",
    minPrice: 45000000,
    maxPrice: 70000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "TP. Biên Hòa",
    ward: "Phường Phước Tân",
    street: "Quốc lộ 51",
    minPrice: 40000000,
    maxPrice: 65000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "TP. Biên Hòa",
    ward: "Phường Tam Phước",
    street: "Quốc lộ 51",
    minPrice: 38000000,
    maxPrice: 60000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "TP. Biên Hòa",
    ward: "Phường Bình Lộc",
    street: "Đường N5",
    minPrice: 35000000,
    maxPrice: 55000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "TP. Biên Hòa",
    ward: "Phường Tân Triều",
    street: "Đường 768",
    minPrice: 30000000,
    maxPrice: 50000000,
    landType: "Thổ cư",
  },

  // TP. Long Khánh
  {
    province: "Đồng Nai",
    district: "TP. Long Khánh",
    ward: "Phường Long Khánh",
    street: "Đường Cách Mạng Tháng Tám",
    minPrice: 45000000,
    maxPrice: 70000000,
    landType: "Thương mại-Dịch vụ",
  },
  {
    province: "Đồng Nai",
    district: "TP. Long Khánh",
    ward: "Phường Long Khánh",
    street: "Quốc lộ 1A",
    minPrice: 40000000,
    maxPrice: 65000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "TP. Long Khánh",
    ward: "Phường Bảo Vinh",
    street: "Đường Duy Tân",
    minPrice: 35000000,
    maxPrice: 55000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "TP. Long Khánh",
    ward: "Phường Xuân Lập",
    street: "Quốc lộ 1",
    minPrice: 32000000,
    maxPrice: 50000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "TP. Long Khánh",
    ward: "Phường Hàng Gòn",
    street: "Quốc lộ 56",
    minPrice: 28000000,
    maxPrice: 45000000,
    landType: "Thổ cư",
  },

  // Huyện Trảng Bom
  {
    province: "Đồng Nai",
    district: "Huyện Trảng Bom",
    ward: "Xã Trảng Bom",
    street: "Đường Nguyễn Hữu Cảnh",
    minPrice: 25000000,
    maxPrice: 40000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "Huyện Trảng Bom",
    ward: "Xã An Viễn",
    street: "Đường DT777",
    minPrice: 20000000,
    maxPrice: 35000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "Huyện Trảng Bom",
    ward: "Xã Bàu Hàm",
    street: "Đường Trảng Bom - Cây Gáo",
    minPrice: 18000000,
    maxPrice: 30000000,
    landType: "Nông nghiệp",
  },
  {
    province: "Đồng Nai",
    district: "Huyện Trảng Bom",
    ward: "Xã Hưng Thịnh",
    street: "Quốc lộ 1A",
    minPrice: 22000000,
    maxPrice: 38000000,
    landType: "Thổ cư",
  },

  // Huyện Xuân Lộc
  {
    province: "Đồng Nai",
    district: "Huyện Xuân Lộc",
    ward: "Xã Xuân Lộc",
    street: "Đường Hoàng Văn Thụ",
    minPrice: 20000000,
    maxPrice: 35000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "Huyện Xuân Lộc",
    ward: "Xã Xuân Định",
    street: "Quốc lộ 1A",
    minPrice: 18000000,
    maxPrice: 30000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "Huyện Xuân Lộc",
    ward: "Xã Xuân Phú",
    street: "Quốc lộ 1A",
    minPrice: 16000000,
    maxPrice: 28000000,
    landType: "Nông nghiệp",
  },
  {
    province: "Đồng Nai",
    district: "Huyện Xuân Lộc",
    ward: "Xã Xuân Hòa",
    street: "Quốc lộ 1A",
    minPrice: 15000000,
    maxPrice: 25000000,
    landType: "Nông nghiệp",
  },

  // Huyện Long Thành
  {
    province: "Đồng Nai",
    district: "Huyện Long Thành",
    ward: "Xã Long Thành",
    street: "Đường Trần Quốc Toản",
    minPrice: 50000000,
    maxPrice: 80000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "Huyện Long Thành",
    ward: "Xã An Phước",
    street: "Ấp 7",
    minPrice: 35000000,
    maxPrice: 55000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "Huyện Long Thành",
    ward: "Xã Bình An",
    street: "Đường Nguyễn Thi Giờ",
    minPrice: 40000000,
    maxPrice: 65000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "Huyện Long Thành",
    ward: "Xã Long Phước",
    street: "Ấp Phước Hòa",
    minPrice: 38000000,
    maxPrice: 60000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "Huyện Long Thành",
    ward: "Xã Đại Phước",
    street: "Đường Lý Thái Tổ",
    minPrice: 45000000,
    maxPrice: 70000000,
    landType: "Thổ cư",
  },

  // Huyện Nhơn Trạch
  {
    province: "Đồng Nai",
    district: "Huyện Nhơn Trạch",
    ward: "Xã Nhơn Trạch",
    street: "Đường Phạm Văn Thuận",
    minPrice: 30000000,
    maxPrice: 50000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "Huyện Nhơn Trạch",
    ward: "Xã Phước An",
    street: "Đường Hùng Vương",
    minPrice: 28000000,
    maxPrice: 45000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "Huyện Nhơn Trạch",
    ward: "Xã Bình Minh",
    street: "Đường 65",
    minPrice: 25000000,
    maxPrice: 40000000,
    landType: "Nông nghiệp",
  },

  // Huyện Thống Nhất
  {
    province: "Đồng Nai",
    district: "Huyện Thống Nhất",
    ward: "Xã Dầu Giây",
    street: "Quốc lộ 1A",
    minPrice: 22000000,
    maxPrice: 38000000,
    landType: "Thổ cư",
  },
  {
    province: "Đồng Nai",
    district: "Huyện Thống Nhất",
    ward: "Xã Gia Kiệm",
    street: "Ấp Nam Sơn",
    minPrice: 18000000,
    maxPrice: 30000000,
    landType: "Nông nghiệp",
  },
  {
    province: "Đồng Nai",
    district: "Huyện Thống Nhất",
    ward: "Xã Thống Nhất",
    street: "Quốc lộ 20",
    minPrice: 20000000,
    maxPrice: 35000000,
    landType: "Thổ cư",
  },
]
